versin: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-node-browsers
      - image: circleci/mysql:5.7
        command: mysqld --default-authentication-plugin=mysql_native_password
    working_directory: ~/project
    steps:
      - checkout
      - run: docker-compose up -d --build
      - run: docker-compose exec app composer install
      - run: cp .env.circleci .env
      - run: docker-compose exec app php artisan key:generate
      - run:
      - run: docker-compose exec app php artisan migrate:refresh
      - run: docker-compose exec app vendor/bin/phpunit tests/Feature
