versin: 2
jobs:
  build:
    machine: true
    working_directory: ~/project
    steps:
      - checkout
      - run: docker-compose down --volumes --rmi all
      - run: docker-compose up -d --build
      - run: docker-compose stop
      - run: docker-compose restart
      - run: |
          docker-compose exec app ash
          composer install
          cp .env.circleci .env
          php artisan key:generate
          php artisan migrate
          vendor/bin/phpunit tests/Feature
