versin: 2
jobs:
  build:
    machine: true
    working_directory: ~/project
    steps:
      - checkout
      - run: docker-compose up -d --build
      - run: docker-compose exec app composer install
      - run: cp .env.circleci .env
      - run: docker-compose exec app php artisan key:generate
      - run: docker-compose exec app php artisan migrate:refresh
      - run: docker-compose exec app vendor/bin/phpunit tests/Feature
