versin: 2
jobs:
  build:
    machine: true
    working_directory: ~/project
    steps:
      - checkout
      - run: docker-compose down --volumes --rmi all
      - run: docker-compose up -d --build
      - run: docker-compose stop
      - run: docker-compose restart
      - run: docker-compose exec app ash
      - run: composer install
      - run: cp .env.circleci .env
      - run: php artisan key:generate
      - run: php artisan migrate
      - run: vendor/bin/phpunit tests/Feature
